name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]


jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore PawPal/PawPal.sln

      - name: Run tests
        run: dotnet test PawPal/Tests/Tests.csproj --configuration Release --no-restore --verbosity normal

  build-and-publish:
    name: Build and publish Docker image
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      - name: List directory content to debug
        run: |
          echo "Repository root content:"
          ls -la
          echo "PawPal directory content:"
          ls -la PawPal || echo "PawPal directory not found"
          
      - name: Restore dependencies
        run: dotnet restore PawPal/PawPal.sln
        
      - name: Build
        run: dotnet build PawPal/PawPal.sln --configuration Release --no-restore
        
      - name: Test
        run: dotnet test PawPal/PawPal.sln --configuration Release --no-build
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pawpal:latest,${{ secrets.DOCKER_USERNAME }}/pawpal:${{ github.sha }}