name: CI Pipeline

on:
  pull_request:
    branches: [ '*' ]


jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore PawPal/PawPal.sln

      - name: Run tests
        run: dotnet test PawPal/Tests/Tests.csproj --configuration Release --no-restore --verbosity normal